import Head from "next/head";
import Link from "next/link";
import { getAllPublished } from "@/lib/notion";

interface Props {
  posts: any;
}

export default function Home({ posts }: Props) {
  if (!posts) return <h1>No posts</h1>;

  return (
    <div>
      <Head>
        <title>My Blog</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="max-w-3xl mx-auto my-40">
        <h1 className="scroll-m-20 text-4xl font-extrabold tracking-tight lg:text-5xl">
          Artikel Rumpun
        </h1>

        {posts.map((post: any, index: any) => (
          <section key={index}>
            <div>
              <h2 className="mt-8 scroll-m-20 text-2xl font-semibold tracking-tight hover:underline">
                <Link href={`articles/${post.slug}`}>{post.title}</Link>
              </h2>
            </div>
            <div>{post.date}</div>
            <p>{post.description}</p>
          </section>
        ))}
      </main>
    </div>
  );
}

export const getStaticProps = async () => {
  const data = await getAllPublished();

  return {
    props: {
      posts: data,
    },
    revalidate: 60,
  };
};
